//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovoVivoCaminho.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Membros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Membros()
        {
            this.Dizimos = new HashSet<Dizimos>();
        }
    
        public int ID { get; set; }
        public int IDIgreja { get; set; }
        public Nullable<int> IDEquipe { get; set; }
        [StringLength(250, ErrorMessage = "Tamanho máximo de 250 caracteres.")]
        public string Nome { get; set; }
        [StringLength(250, ErrorMessage = "Tamanho máximo de 250 caracteres.")]
        public string Tipo { get; set; }
        [StringLength(250, ErrorMessage = "Tamanho máximo de 250 caracteres.")]
        public string Endereco { get; set; }
        [StringLength(250, ErrorMessage = "Tamanho máximo de 250 caracteres.")]
        public string Numero { get; set; }
        [StringLength(250, ErrorMessage = "Tamanho máximo de 250 caracteres.")]
        public string Complemento { get; set; }
        [StringLength(250, ErrorMessage = "Tamanho máximo de 250 caracteres.")]
        public string Bairro { get; set; }
        [StringLength(250, ErrorMessage = "Tamanho máximo de 250 caracteres.")]
        public string Cidade { get; set; }
        [StringLength(2, ErrorMessage = "Tamanho máximo de  caracteres. Exemplo: SP")]
        public string UF { get; set; }
        [StringLength(8, ErrorMessage = "Tamanho máximo de  caracteres. Exemplo: 00000000")]
        public string CEP { get; set; }
        [StringLength(2, ErrorMessage = "Tamanho máximo de  caracteres. Exemplo: 11")]
        public string DDD { get; set; }
        [StringLength(9, ErrorMessage = "Tamanho máximo de  caracteres. Exemplo: 999999999")]
        public string Fone { get; set; }
        [StringLength(50, ErrorMessage = "Tamanho máximo de 50 caracteres.")]
        public string EstadoCivil { get; set; }
        public bool Batizado { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> DataDeNascimento { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> MembroDesde { get; set; }
    
        public virtual Equipes Equipes { get; set; }
        public virtual Igrejas Igrejas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dizimos> Dizimos { get; set; }
    }
}
